# A Quick Introduction to Numerical Data Manipulation with Python and NumPy


## What is NumPy?

[NumPy](https://docs.scipy.org/doc/numpy/index.html) stands for numerical Python. It's the backbone of all kinds of scientific and numerical computing in Python.

And since machine learning is all about turning data into numbers and then figuring out the patterns, NumPy often comes into play.

<img src="../images/numpy-6-step-ml-framework-tools-numpy-highlight.png" alt="a 6 step machine learning framework along will tools you can use for each step" width="700"/>

## Why NumPy?

You can do numerical calculations using pure Python. In the beginning, you might think Python is fast but once your data gets large, you'll start to notice slow downs.

One of the main reasons you use NumPy is because it's fast. Behind the scenes, the code has been optimized to run using C. Which is another programming language, which can do things much faster than Python.

The benefit of this being behind the scenes is you don't need to know any C to take advantage of it. You can write your numerical computations in Python using NumPy and get the added speed benefits.

If your curious as to what causes this speed benefit, it's a process called vectorization. [Vectorization](https://en.wikipedia.org/wiki/Vectorization) aims to do calculations by avoiding loops as loops can create potential bottlenecks.

NumPy achieves vectorization through a process called [broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#module-numpy.doc.broadcasting).

##### NOTE:
Vectors and matrices are often referred to by the general term arrays. A vector is an array of 1 row x n columns (row vector) or 1 column x n rows (column vector), while a matrix is an array of m rows x n columns.

However, Numpy also offers seperate metrices function. Numpy matrices are strictly 2-dimensional, while numpy arrays (ndarrays) are N-dimensional. Matrix objects are a subclass of ndarray, so they inherit all the attributes and methods of ndarrays.

The main advantage of numpy matrices is that they provide a convenient notation for matrix multiplication: if a and b are matrices, then a*b is their matrix product
Arrays in Real Life:
.In real life, arrays are used whenever items must be put in an orderly manner. One of the easiest examples is a seating chart in theaters or a classroom, which is a 2D array that can be accessed by seat numbers, which are stored in rows and columns.




## What does this notebook cover?

The NumPy library is very capable. However, learning everything off by heart isn't necessary. Instead, this notebook focuses on the main concepts of NumPy and the `ndarray` datatype.

You can think of the `ndarray` datatype as a very flexible array of numbers.

More specifically, we'll look at:
* NumPy datatypes & attributes
* Creating arrays
* Viewing arrays & matrices (indexing)
* Manipulating & comparing arrays
* Sorting arrays
* Use cases (examples of turning things into numbers)

After going through it, you'll have the base knolwedge of NumPy you need to keep moving forward.

## Where can I get help?
If you get stuck or think of something you'd like to do which this notebook doesn't cover, don't fear!

The recommended steps you take are:
1. **Try it** - Since NumPy is very friendly, your first step should be to use what you know and try figure out the answer to your own question (getting it wrong is part of the process). If in doubt, run your code.
2. **Search for it** - If trying it on your own doesn't work, since someone else has probably tried to do something similar, try searching for your problem. You'll likely end up in 1 of 2 places:
    * [NumPy documentation](https://docs.scipy.org/doc/numpy/index.html) - the ground truth for everything NumPy, this resource covers all of the NumPy functionality.
    * [Stack Overflow](https://stackoverflow.com/) - this is the developers Q&A hub, it's full of questions and answers of different problems across a wide range of software development topics and chances are, there's one related to your problem.
    
An example of searching for a NumPy function might be:

> "how to find unique elements in a numpy array"

Searching this on Google leads to the NumPy documentation for the `np.uniquie()` function: https://docs.scipy.org/doc/numpy/reference/generated/numpy.unique.html

The next steps here are to read through the documentation, check the examples and see if they line up to the problem you're trying to solve. If they do, **rewrite the code** to suit your needs, run it, and see what the outcomes are.

3. **Ask for help** - If you've been through the above 2 steps and you're still stuck, you might want to ask your question on [Stack Overflow](https://www.stackoverflow.com). Be as specific as possible and provide details on what you've tried.

Remember, you don't have to learn all of the functions off by heart to begin with. 

What's most important is continually asking yourself, "what am I trying to do with the data?".

Start by answering that question and then practicing finding the code which does it.

Let's get started.

## 0. Importing NumPy

To get started using NumPy, the first step is to import it. 

The most common way (and method you should use) is to import NumPy as the abbreviation `np`.

If you see the letters `np` used anywhere in machine learning or data science, it's probably referring to the NumPy library.

In [57]:
import numpy as np

## 1. DataTypes and attributes

**NOTE:** Important to remember the main type in NumPy is `ndarray`, even seemingly different kinds of arrays are still `ndarray`'s. This means an operation you do on one array, will work on another.

In [58]:
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3])

# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6]])

# 3-dimensional array, also referred to as n-dimmentional array

a3=np.array([
    
    [



        [1,2,3],
        [4,5,6]
        
]

    
])



a4 = np.array([
                [
                [1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]
                ],
                
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18],
                ]])




In [59]:
a1,a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

(array([1, 2, 3]), (3,), 1, dtype('int32'), 3, numpy.ndarray)

In [60]:
a2,a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

(array([[1. , 2. , 3.3],
        [4. , 5. , 6. ]]),
 (2, 3),
 2,
 dtype('float64'),
 6,
 numpy.ndarray)

In [61]:
a3,a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

(array([[[1, 2, 3],
         [4, 5, 6]]]),
 (1, 2, 3),
 3,
 dtype('int32'),
 6,
 numpy.ndarray)

In [62]:
a4,a4.shape,a4.ndim 


#read it like: there are two arrays of 3 x 3 dimensions - and the shape shows that this is a 3 dimmensional array

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 (2, 3, 3),
 3)

### Anatomy of an array

<img src="../project_files/images/numpy-anatomy-of-an-array-updated.png" alt="anatomy of a numpy array"/>

Key terms:
* **Array** - A list of numbers, can be multi-dimensional.
* **Scalar** - A single number (e.g. `7`).
* **Vector** - A list of numbers with 1-dimesion (e.g. `np.array([1, 2, 3])`).
* **Matrix** - A (usually) multi-deminsional list of numbers (e.g. `np.array([[1, 2, 3], [4, 5, 6]])`).

### pandas DataFrame out of NumPy arrays

This is to examplify how NumPy is the backbone of many other libraries.

In [63]:
import pandas as pd
df = pd.DataFrame(np.random.randint(10, size=(5, 3)), #10 will keep the generated numbers within limit of 10
                                    columns=['a', 'b', 'c'])
df

a  b  c
0  2  0  8
1  9  3  4
2  3  9  0
3  7  2  6
4  8  1  8

In [64]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6. ]])

In [65]:
df2 = pd.DataFrame(a2)
df2

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.0

## 2. Creating arrays

* `np.array()`
* `np.ones()`
* `np.zeros()`
* `np.arrange()`
* `np.random.rand(5, 3)`
* `np.random.randint(10, size=5)`
* `np.random.seed()` - pseudo random numbers

* Searching the documentation example (finding `np.unique()` and using it)

In [66]:
# Create a simple array
simple_array = np.array([1, 2, 3])
simple_array,simple_array.dtype

(array([1, 2, 3]), dtype('int32'))

In [67]:
# Create an array of ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [68]:
# The default datatype is 'float64'
ones.dtype

dtype('float64')

In [69]:
# You can change the datatype with .astype()
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [70]:
# Create an array of zeros
zeros = np.zeros((5, 3, 3)) # 5 arrays of 3 x 3 size 
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [74]:
zeros.dtype,zeros.ndim,zeros.size

(dtype('float64'), 3, 45)

In [19]:
# Create an array within a range of values
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
# Random array
random_array = np.random.randint(10, size=(5, 3))
random_array

array([[5, 1, 3],
       [2, 1, 4],
       [1, 1, 5],
       [2, 2, 7],
       [7, 2, 0]])

In [24]:
# Random array of floats (between 0 & 1)
np.random.random((5, 3))

array([[0.41158209, 0.76405891, 0.51988195],
       [0.57957216, 0.5790568 , 0.98047138],
       [0.94403281, 0.26176105, 0.76894282],
       [0.0923087 , 0.97259402, 0.8107423 ],
       [0.46999535, 0.11551971, 0.43389067]])

In [75]:
# Random 5x3 array of floats (between 0 & 1), similar to above
np.random.rand(5, 3)

array([[0.24074431, 0.39175146, 0.61657214],
       [0.63607418, 0.58866311, 0.07227901],
       [0.65097618, 0.98660184, 0.05049899],
       [0.2480745 , 0.80422195, 0.36594867],
       [0.26135344, 0.47881407, 0.54583486]])

In [29]:
np.random.randn(5, 3) #normally distributed numbers are generated

array([[-0.00973593,  0.9623002 , -0.21729789],
       [ 1.83230106, -0.13222083,  0.4476791 ],
       [-0.37867236, -0.29665971, -1.06782169],
       [-1.69460063, -1.65694494, -0.46011383],
       [-1.21897752,  0.73213916, -1.0802702 ]])

NumPy uses pseudo-random numbers, which means, the numbers look random but aren't really, they're predetermined.

For consistency, you might want to keep the random numbers you generate similar throughout experiments.

To do this, you can use [`np.random.seed()`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html).

What this does is it tells NumPy, "Hey, I want you to create random numbers but keep them aligned with the seed."

Let's see it.

In [151]:
# Set random seed to 0
np.random.seed(0)

# Make 'random' numbers
np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

With `np.random.seed()` set, every time you run the cell above, the same random numbers will be generated.

What if `np.random.seed()` wasn't set?

Every time you run the cell below, a new set of numbers will appear.

In [152]:
# Make more random numbers
np.random.randint(10, size=(5, 3))

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

Let's see it in action again, we'll stay consistent and set the random seed to 0.

In [153]:
# Set random seed to same number as above
np.random.seed(0)

# The same random numbers come out
np.random.randint(10, size=(5, 3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

Because `np.random.seed()` is set to 0, the random numbers are the same as the cell with `np.random.seed()` set to 0 as well.

Setting `np.random.seed()` is not 100% necessary but it's helpful to keep numbers the same throughout your experiments.

For example, say you wanted to split your data randomly into training and test sets.

Every time you randomly split, you might get different rows in each set.

If you shared your work with someone else, they'd get different rows in each set too.

Setting `np.random.seed()` ensures there's still randomness, it just makes the randomness repeatable. Hence the 'pseudo-random' numbers.

In [154]:
np.random.seed(0)
df = pd.DataFrame(np.random.randint(10, size=(5, 3)))
df

0  1  2
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1

### What unique values are in the array a3?

Now you've seen a few different ways to create arrays, as an exercise, try find out what NumPy function you could use to find the unique values are within the `a3` array.

You might want to search some like, "how to find the unqiue values in a numpy array".

In [32]:
# Your code here

a3,np.unique(a3)

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18]))

## 3. Viewing arrays and matrices (indexing)

Remember, because arrays and matrices are both `ndarray`'s, they can be viewed in similar ways.

Let's check out our 3 arrays again.

In [156]:
a1

array([1, 2, 3])

In [157]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [189]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [55]:
a=np.random.randint(10,size=(2,3,2,5))
np.ndim(a),a


(4,
 array([[[[0, 5, 2, 6, 3],
          [5, 1, 4, 7, 5]],
 
         [[5, 7, 8, 8, 7],
          [1, 5, 5, 8, 7]],
 
         [[9, 3, 1, 9, 9],
          [1, 8, 5, 6, 0]]],
 
 
        [[[8, 8, 3, 2, 5],
          [5, 9, 6, 1, 6]],
 
         [[6, 1, 6, 4, 6],
          [2, 7, 1, 7, 4]],
 
         [[0, 3, 1, 8, 9],
          [2, 1, 5, 1, 3]]]]))

Note: Array shapes are always listed in the format `(row, column, n, n, n...)` where `n` is optional extra dimensions.

In [60]:
a1,a1[0]

(array([1, 2, 3]), 1)

In [62]:
a2,a2[0]

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([1. , 2. , 3.3]))

In [63]:
a3,a3[0]

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [162]:
# Get 2nd row (index 1) of a2
a2[1]

array([4. , 5. , 6.5])

In [163]:
# Get the first 2 values of the first 2 rows of both arrays
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

This takes a bit of practice, especially when the dimensions get higher. Usually, it takes me a little trial and error of trying to get certain values, viewing the output in the notebook and trying again.

##### NumPy arrays get printed from outside to inside. This means the number at the end of the shape comes first, and the number at the start of the shape comes last.

In [68]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[5, 3, 4, 7, 2],
         [9, 4, 9, 7, 8],
         [2, 4, 5, 4, 0],
         [5, 1, 1, 0, 0]],

        [[1, 5, 4, 3, 7],
         [9, 3, 5, 3, 0],
         [0, 5, 5, 6, 8],
         [9, 3, 7, 0, 0]],

        [[1, 8, 4, 3, 0],
         [5, 1, 2, 5, 8],
         [8, 3, 5, 5, 9],
         [6, 4, 8, 7, 5]]],


       [[[0, 5, 4, 4, 7],
         [1, 1, 7, 2, 2],
         [0, 0, 2, 9, 8],
         [3, 4, 9, 6, 2]],

        [[8, 7, 3, 0, 1],
         [9, 0, 5, 4, 3],
         [7, 8, 6, 5, 6],
         [7, 7, 8, 1, 4]],

        [[4, 7, 3, 3, 2],
         [2, 9, 8, 9, 3],
         [6, 0, 8, 9, 4],
         [7, 9, 1, 1, 6]]]])

In [69]:
a4.shape

(2, 3, 4, 5)

In [70]:
# Get only the first 4 numbers of each single vector
a4[:, :, :, :4]

array([[[[5, 3, 4, 7],
         [9, 4, 9, 7],
         [2, 4, 5, 4],
         [5, 1, 1, 0]],

        [[1, 5, 4, 3],
         [9, 3, 5, 3],
         [0, 5, 5, 6],
         [9, 3, 7, 0]],

        [[1, 8, 4, 3],
         [5, 1, 2, 5],
         [8, 3, 5, 5],
         [6, 4, 8, 7]]],


       [[[0, 5, 4, 4],
         [1, 1, 7, 2],
         [0, 0, 2, 9],
         [3, 4, 9, 6]],

        [[8, 7, 3, 0],
         [9, 0, 5, 4],
         [7, 8, 6, 5],
         [7, 7, 8, 1]],

        [[4, 7, 3, 3],
         [2, 9, 8, 9],
         [6, 0, 8, 9],
         [7, 9, 1, 1]]]])

`a4`'s shape is (2, 3, 4, 5), this means it gets displayed like so:
* Inner most array = size 5
* Next array = size 4
* Next array = size 3
* Outer most array = size 2

* MY EXPLAINATIION: GROUP OF 2 ARRAYS, WITH 3 INNNER GROUPS, EACH INNER GROUP HAS 4 X 5 SIZE ARRAY IN IT.

## 4. Manipulating and comparying arrays
* Arithmetic
    * `+`, `-`, `*`, `/`, `//`, `**`, `%`
    * `np.exp()`
    * `np.log()`
    * [Dot product](https://www.mathsisfun.com/algebra/matrix-multiplying.html) - `np.dot()`
    * Broadcasting
* Aggregation
    * `np.sum()` - faster than `.sum()`, make demo, np is really fast
    * `np.mean()`
    * `np.std()`
    * `np.var()`
    * `np.min()`
    * `np.max()`
    * `np.argmin()` - find index of minimum value
    * `np.argmax()` - find index of maximum value
    * These work on all `ndarray`'s
        * `a4.min(axis=0)` -- you can use axis as well
* Reshaping
    * `np.reshape()`
* Transposing
    * `a3.T` 
* Comparison operators
    * `>`
    * `<`
    * `<=`
    * `>=`
    * `x != 3`
    * `x == 3`
    * `np.sum(x > 3)`

### Arithmetic

In [167]:
a1

array([1, 2, 3])

In [168]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [169]:
# Add two arrays
a1 + ones

array([2., 3., 4.])

In [170]:
# Subtract two arrays
a1 - ones

array([0., 1., 2.])

In [171]:
# Multiply two arrays
a1 * ones

array([1., 2., 3.])

In [77]:
# Multiply two arrays
a1,a2,a1 * a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6. ]]),
 array([[ 1. ,  4. ,  9.9],
        [ 4. , 10. , 18. ]]))

In [188]:
a1.shape, a2.shape

((3,), (2, 3))

In [174]:
#a2 * a3

In [176]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. 

    - Broadcasting is a feature of NumPy which performs an operation across multiple dimensions of data without replicating the data. This saves time and space. For example, if you have a 3x3 array (A) and want to add a 1x3 array (B), NumPy will add the row of (B) to every row of (A).

- Rules of Broadcasting
    1. If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
    2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
    3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.
    
    
**The broadcasting rule:**
In order to broadcast, the size of the trailing axes for both arrays in an operation must be either the same size or one of them must be one.

In [72]:
a1

array([1, 2, 3])

In [73]:
a1.shape

(3,)

In [74]:
a2.shape

(2, 3)

In [75]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [184]:
a1 + a2

array([[2. , 4. , 6.3],
       [5. , 7. , 9.5]])

In [76]:
a2 + 2

array([[3. , 4. , 5.3],
       [6. , 7. , 8.5]])

In [77]:
# Raises an error because there's a shape mismatch
a2 + a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
# Divide two arrays
a1 / ones

In [80]:
# Divide using floor division
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [ ]:
# Take an array to a power
a1 ** 2

In [ ]:
# You can also use np.square()
np.square(a1)

In [ ]:
# Modulus divide (what's the remainder?)
a1 % 2

You can also find the log or exponential of an array using `np.log()` and `np.exp()`.

In [ ]:
# Find the log of an array
np.log(a1)

In [ ]:
# Find the exponential of an array
np.exp(a1)

### Aggregation

Aggregation - bringing things together, doing a similar thing on a number of things.

In [81]:
sum(a1)

6

In [82]:
np.sum(a1)

6

Use NumPy's `np.sum()` on NumPy arrays and Python's `sum()` on Python lists.

In [111]:
massive_array = np.random.random(10000000)
massive_array.size

10000000

In [112]:
%timeit sum(massive_array) # Python sum()
%timeit np.sum(massive_array) # NumPy np.sum()

1.15 s ± 8.98 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
13.1 ms ± 151 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [106]:
import random 
massive_list = [random.randint(0, 12) for i in range(10000000)]
len(massive_list)

10000000

In [107]:
massive_list[:10]

[1, 10, 7, 11, 5, 5, 3, 1, 12, 2]

In [108]:
a=%timeit sum(massive_list)
b=%timeit np.sum(massive_list)
        

69.4 ms ± 1.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
984 ms ± 14.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [110]:
a2


array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
# Find the mean
np.mean(a2)

In [ ]:
# Find the max
np.max(a2)

In [ ]:
# Find the min
np.min(a2)

In [ ]:
# Find the standard deviation
np.std(a2)

In [ ]:
# Find the variance
np.var(a2)

In [ ]:
# The standard deviation is the square root of the variance
np.sqrt(np.var(a2))

**What's mean?**

Mean is the same as average. You can find the average of a set of numbers by adding them up and dividing them by how many there are.

**What's standard deviation?**

[Standard deviation](https://www.mathsisfun.com/data/standard-deviation.html) is a measure of how spread out numbers are.

**What's variance?**

The [variance](https://www.mathsisfun.com/data/standard-deviation.html) is the averaged squared differences of the mean.

To work it out, you:
1. Work out the mean
2. For each number, subtract the mean and square the result
3. Find the average of the squared differences

In [ ]:
# Demo of variance
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
# The standard deviation is the square root of the variance
np.sqrt(np.var(high_var_array))

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

### Reshaping

In [113]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [114]:
a2.shape

(2, 3)

In [115]:
a2 + a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [116]:
a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [ ]:
a2.reshape(2, 3, 1) + a3

### Transpose

In [ ]:
a2.shape

In [ ]:
a2.T

In [ ]:
a2.T.shape

In [118]:
matrix = np.random.random(size=(5,3,3))
matrix

array([[[0.94964498, 0.45451526, 0.09295938],
        [0.11441011, 0.4434066 , 0.19548644],
        [0.84032304, 0.52756718, 0.69859695]],

       [[0.31971125, 0.85486008, 0.3101591 ],
        [0.18691201, 0.76735488, 0.58682994],
        [0.72418992, 0.55327703, 0.07666874]],

       [[0.81086201, 0.20436598, 0.07454752],
        [0.81241683, 0.82401582, 0.17428379],
        [0.68622637, 0.83858866, 0.25973546]],

       [[0.75528521, 0.08685825, 0.07331053],
        [0.55199233, 0.78790666, 0.79873463],
        [0.68484995, 0.37531516, 0.63167605]],

       [[0.51133032, 0.1843698 , 0.92890974],
        [0.27971714, 0.7336055 , 0.44036304],
        [0.20652237, 0.69462607, 0.83827179]]])

In [119]:
matrix.shape

(5, 3, 3)

In [120]:
matrix.T

array([[[0.94964498, 0.31971125, 0.81086201, 0.75528521, 0.51133032],
        [0.11441011, 0.18691201, 0.81241683, 0.55199233, 0.27971714],
        [0.84032304, 0.72418992, 0.68622637, 0.68484995, 0.20652237]],

       [[0.45451526, 0.85486008, 0.20436598, 0.08685825, 0.1843698 ],
        [0.4434066 , 0.76735488, 0.82401582, 0.78790666, 0.7336055 ],
        [0.52756718, 0.55327703, 0.83858866, 0.37531516, 0.69462607]],

       [[0.09295938, 0.3101591 , 0.07454752, 0.07331053, 0.92890974],
        [0.19548644, 0.58682994, 0.17428379, 0.79873463, 0.44036304],
        [0.69859695, 0.07666874, 0.25973546, 0.63167605, 0.83827179]]])

In [121]:
matrix.T.shape

(3, 3, 5)

### Dot

* TODO - create graphic for dot versus element-wise also known as Hadamard product
* TODO - why would someone use dot versus element-wise?
* A dot product models real world problems well, it's a method of finding patterns between data 

In [207]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(3, 3))
mat2 = np.random.randint(10, size=(3, 2))

mat1.shape, mat2.shape

((3, 3), (3, 2))

In [208]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [204]:
mat2

array([[0, 6],
       [4, 2],
       [4, 6]])

In [206]:
np.dot(mat1, mat2), mat1*mat2

ValueError: operands could not be broadcast together with shapes (100,3) (3,2) 

In [192]:
np.random.seed(0)
mat3 = np.random.randint(10, size=(4,3))
mat4 = np.random.randint(10, size=(4,3))
mat3

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6]])

In [193]:
mat4

array([[8, 8, 1],
       [6, 7, 7],
       [8, 1, 5],
       [9, 8, 9]])

In [196]:
np.dot(mat3, mat4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [197]:
mat3.T.shape

(3, 4)

In [198]:
# Dot product
np.dot(mat3.T, mat4)

array([[118,  96,  77],
       [145, 110, 137],
       [148, 137, 130]])

In [200]:
# Element-wise multiplication, also known as Hadamard product
mat3 * mat4

array([[40,  0,  3],
       [18, 49, 63],
       [24,  5, 10],
       [36, 56, 54]])

### Dot product practical example, nut butter sales

In [154]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [155]:
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [156]:
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [157]:
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=["Price"],
                             columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices.shape

(1, 3)

In [158]:
weekly_sales.shape

(5, 3)

In [163]:
# Find the total amount of sales for a whole day
total_sales = prices.dot(sales_amounts)
total_sales

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

The shapes aren't aligned, we need the middle two numbers to be the same.

In [164]:
prices

array([10,  8, 12])

In [165]:
sales_amounts.T.shape

(3, 5)

In [166]:
# To make the middle numbers the same, we can transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [167]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [168]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [169]:
# Need to transpose again
weekly_sales["Total"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total
Mon               12             15              0    240
Tues               3              3              7    138
Wed                9             19             18    458
Thurs              4              6             12    232
Fri                1              6              7    142

### Comparison operators 

In [209]:
a1

array([1, 2, 3])

In [210]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [211]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [ ]:
a1 >= a2

In [212]:
a1 > 5

array([False, False, False])

In [213]:
a1 == a1

array([ True,  True,  True])

In [214]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

## 5. Sorting arrays

* `np.sort()`
* `np.argsort()`
* `np.argmax()`
* `np.argmin()`

In [217]:
random_array

array([[5, 1, 3],
       [2, 1, 4],
       [1, 1, 5],
       [2, 2, 7],
       [7, 2, 0]])

In [218]:
np.sort(random_array)

array([[1, 3, 5],
       [1, 2, 4],
       [1, 1, 5],
       [2, 2, 7],
       [0, 2, 7]])

In [219]:
np.argsort(random_array)

array([[1, 2, 0],
       [1, 0, 2],
       [0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [220]:
a1

array([1, 2, 3])

In [221]:
# Return the indices that would sort an array
np.argsort(a1)



array([0, 1, 2], dtype=int64)

In [226]:
# No axis
np.argmin(a1)

0

In [227]:
random_array

array([[5, 1, 3],
       [2, 1, 4],
       [1, 1, 5],
       [2, 2, 7],
       [7, 2, 0]])

In [228]:
# Across the horizontal (row wise)

np.argmax(random_array, axis=1)

array([0, 2, 2, 2, 0], dtype=int64)

In [229]:
# Down the vertical (column wise)
np.argmin(random_array, axis=0)

array([2, 0, 4], dtype=int64)

## 6. Use case

Turning an image of a panda into numbers.

<img src="../images/numpy-panda.png" alt="photo of a panda waving" />

In [236]:
from matplotlib.image import imread

panda = imread('\numpy-panda.png')
print(type(panda))

OSError: [Errno 22] Invalid argument: '\numpy-panda.png'

In [237]:
panda.shape

NameError: name 'panda' is not defined

In [238]:
panda

NameError: name 'panda' is not defined

<img src="../images/numpy-car-photo.png" alt="photo of a car"/>

In [ ]:
car = imread("../images/numpy-car-photo.png")
car.shape

In [ ]:
car[:,:,:3].shape

<img src="../images/numpy-dog-photo.png" alt="photo a dog"/>

In [ ]:
dog = imread("../images/numpy-dog-photo.png")
dog.shape

In [181]:

dog

NameError: name 'dog' is not defined