In [9]:
import numpy as np

#Data Type of NumPy




In [10]:
a1=np.array([1,2,3])

In [11]:
a1.shape,a1.ndim,a1.dtype, type(a1)

((3,), 1, dtype('int32'), numpy.ndarray)

In [12]:
a2=np.array([[1,2,3],
             [4,4,6],
             [7,3,9]])

In [13]:
a2.shape,a2.ndim,a2.dtype,type(a2)

((3, 3), 2, dtype('int32'), numpy.ndarray)

In [14]:
a3=np.array([
            [
            [1,2,3],
            ],
            [
            [4,5,6],
            ],
            
                        [
            [7,8,9],
            ],

            ])

#two 1x3 arrays - this is three dimentional array. The shape of all arrays in mutidimentional array should be the same


In [15]:
a3.shape,a3.ndim,a2.dtype,type(a3)

((3, 1, 3), 3, dtype('int32'), numpy.ndarray)

In [16]:
import pandas as pd


In [17]:

my_array=pd.DataFrame(np.random.randint(1100,1500,size=(4,3)),columns=['a','b','c'])

In [18]:
my_array

a     b     c
0  1376  1110  1230
1  1327  1100  1433
2  1211  1225  1381
3  1425  1421  1233

In [19]:
my_array=pd.DataFrame(a2)



In [20]:

my_array

0  1  2
0  1  2  3
1  4  4  6
2  7  3  9

#Creating Arrays in NumPy


In [21]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [22]:
ones=np.ones((2,3))

In [23]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones.dtype

dtype('float64')

In [25]:

zeros=np.zeros((3,2))

In [26]:
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
range_array=np.arange(1,20,2)#start, till, step size

In [28]:
range_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
random_array=np.random.randint(10,20,size=(3,3))

In [30]:
random_array

array([[10, 13, 15],
       [15, 17, 17],
       [18, 10, 19]])

In [31]:
random_array.size

9

In [32]:
random_array.shape

(3, 3)

In [33]:
random_array2=np.random.random((3,4))

In [34]:
random_array2

array([[0.34525175, 0.4800994 , 0.56856254, 0.74130941],
       [0.04432952, 0.57370481, 0.05514076, 0.06131725],
       [0.60907432, 0.6486994 , 0.44666176, 0.0720008 ]])

In [35]:
#to generate random numbers

random_array3=np.random.rand(5,3)

random_array3

array([[0.10422497, 0.3735011 , 0.72279991],
       [0.01253319, 0.28781553, 0.942803  ],
       [0.34444033, 0.7060656 , 0.06988708],
       [0.03268773, 0.91955293, 0.59519432],
       [0.79340667, 0.48349799, 0.13072383]])

In [36]:
#random number change untill we keep seed=contast, may be set to any number

np.random.seed(seed=90)

random_array4=np.random.rand(5,3)

random_array4


array([[0.1530542 , 0.15768566, 0.98549111],
       [0.90449773, 0.18607826, 0.26770951],
       [0.33405116, 0.64459187, 0.25140724],
       [0.63520639, 0.57979778, 0.61881122],
       [0.36777213, 0.25816729, 0.19435019]])

In [37]:
a1


array([1, 2, 3])

In [38]:
np.unique(a2)
a2

array([[1, 2, 3],
       [4, 4, 6],
       [7, 3, 9]])

In [39]:
a3

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [40]:
a2[2][2]

9

In [41]:
a2[:,0] #to access first column of array a2

array([1, 4, 7])

In [42]:
a2[:,2]

array([3, 6, 9])

In [43]:
a2[:]

array([[1, 2, 3],
       [4, 4, 6],
       [7, 3, 9]])

In [44]:
a2[:,2]

array([3, 6, 9])

In [45]:
a3



array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [46]:
a3[1,:]

array([[4, 5, 6]])

In [47]:
a4=np.array([
            [
            [1,2,3]
                
            ],
            [
            [4,5,6],
            ],
            
                        [
            [7,8,9],
            ],

            ])


In [48]:
a4


array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [49]:

a1.shape

(3,)

In [50]:
a1

array([1, 2, 3])

In [51]:
ones=np.ones(3)
ones


array([1., 1., 1.])

In [52]:
a1.shape

(3,)

In [53]:
ones.shape
a2

array([[1, 2, 3],
       [4, 4, 6],
       [7, 3, 9]])

In [54]:
a1+ones

array([2., 3., 4.])

In [55]:
a1*ones

array([1., 2., 3.])

In [56]:
a2.shape


(3, 3)

In [57]:
a1*a2

array([[ 1,  4,  9],
       [ 4,  8, 18],
       [ 7,  6, 27]])

In [58]:
a2.shape

(3, 3)

In [59]:
a21=np.array([[1,2,3],
             
             [4,5,6]])
a21.shape

(2, 3)

In [60]:
(a1*a21)

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [61]:

a3.shape

(3, 1, 3)

In [62]:
a2.shape

(3, 3)

In [63]:
a2*a3

array([[[ 1,  4,  9],
        [ 4,  8, 18],
        [ 7,  6, 27]],

       [[ 4, 10, 18],
        [16, 20, 36],
        [28, 15, 54]],

       [[ 7, 16, 27],
        [28, 32, 54],
        [49, 24, 81]]])

In [64]:
(a2*a3).shape


(3, 3, 3)

In [65]:
a2+a1

array([[ 2,  4,  6],
       [ 5,  6,  9],
       [ 8,  5, 12]])

In [66]:
a2/a1

array([[1. , 1. , 1. ],
       [4. , 2. , 2. ],
       [7. , 1.5, 3. ]])

In [67]:
a2//a1

array([[1, 1, 1],
       [4, 2, 2],
       [7, 1, 3]])

In [68]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [69]:
a1**2 - np.square(a1)


array([0, 0, 0])

In [70]:
a1%a2

array([[0, 0, 0],
       [1, 2, 3],
       [1, 2, 3]])

In [71]:
np.exp(2)

7.38905609893065

In [72]:
sum(a1)

6

In [73]:
massive_array=np.random.rand(10000000)


massive_array.shape

(10000000,)

In [74]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

1.01 s ± 34.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
12.7 ms ± 888 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [75]:
np.mean(a2)

4.333333333333333

In [76]:
np.var(a2)

5.777777777777778

In [77]:

np.sqrt(np.var(a2))

2.4037008503093262

In [78]:
22/7


3.142857142857143

In [79]:
float(22/7)

3.142857142857143

In [80]:
a3.shape

a4=np.array([
             [[1,2,3],
             [4,5,6],
             [7,8,9]],
           
             [
             [1,2,3],
             [4,5,6],
             [7,8,9]
             ]
]  
)           
    
    


In [81]:

a5=np.array([
             [[1],
             [4],
             [7]],
           
             [

                 [1],
             [4],
             [7]
             ]
])

    

In [82]:
a5.shape,a4.shape,a3.shape,a2.shape,a1.shape


((2, 3, 1), (2, 3, 3), (3, 1, 3), (3, 3), (3,))

In [83]:
a5.size,a4.size,a3.size,a2.size,a1.size

(6, 18, 9, 9, 3)

In [84]:
a4.reshape(3,2,3)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]],

       [[4, 5, 6],
        [7, 8, 9]]])

In [85]:
a1.T

array([1, 2, 3])

In [86]:
a1

array([1, 2, 3])

In [87]:
#Boradcasting rule - one of the matrix should have one dimentional axis 
#(which can be multipled with the axis of the other marix)  so it can be expanded to larger size

A=np.random.rand(8,1,3,1) #when 1 dimention is removed, the multiplication error is thrown
B=np.random.rand(7,1,5)




A.shape, B.shape

C=(A*B)
C.shape

(8, 7, 3, 5)

In [88]:
np.random.seed(10)
C=np.random.rand(3,5)
D=np.random.rand(5,3)
CD1=C@D #matrix multiplication 
CD2=np.dot(C,D)

CD1-CD2


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [89]:
C=np.random.randint(10,100,size=(4,3))
D=np.random.randint(10,100,size=(4,3))

E=C*D
E2=np.multiply(C,D)# Matrix multiplication if the arrays are 2-D
F=np.dot(C,D.T)

E,F
F-C@D.T,E-E2


(array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]),
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]))

In [90]:
E-E2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [91]:
np.random.seed(0)
sales_qty_array=np.random.randint(30,size=(5,3))

sales_qty_df=pd.DataFrame(sales_qty_array,index=["Mon","Tue","Wed","Thu","Fri"],
                          columns=["Almond Butter","Peanut Butter","Cashew Butter"])

sales_qty_df

Almond Butter  Peanut Butter  Cashew Butter
Mon             12             15             21
Tue              0              3             27
Wed              3              7              9
Thu             19             21             18
Fri              4             23              6

In [92]:
prices=np.array([1,1,1])

In [93]:
butter_prices=pd.DataFrame(prices.reshape(1,3),index=["Price"],columns=["Almond Butter","Peanut Butter","Cashew Butter"])

In [94]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price              1              1              1

In [95]:
butter_prices.shape


(1, 3)

In [96]:
sales_qty_df


Almond Butter  Peanut Butter  Cashew Butter
Mon             12             15             21
Tue              0              3             27
Wed              3              7              9
Thu             19             21             18
Fri              4             23              6

In [97]:
daily_sales=butter_prices.dot(sales_qty_df.T)

In [98]:
sales_qty_df["Total Sales"] =daily_sales.T


In [99]:
sales_qty_df

Almond Butter  Peanut Butter  Cashew Butter  Total Sales
Mon             12             15             21           48
Tue              0              3             27           30
Wed              3              7              9           19
Thu             19             21             18           58
Fri              4             23              6           33

In [100]:
a1,a2

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 4, 6],
        [7, 3, 9]]))

In [101]:
a1>a2


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [102]:
a1>5,a1<5

(array([False, False, False]), array([ True,  True,  True]))

In [103]:
random_array

array([[10, 13, 15],
       [15, 17, 17],
       [18, 10, 19]])

In [104]:
np.sort(random_array) #sort every axis of the array


array([[10, 13, 15],
       [15, 17, 17],
       [10, 18, 19]])

In [105]:
np.argsort(random_array) #returns the number of indexes on which sorting would happen

array([[0, 1, 2],
       [0, 1, 2],
       [1, 0, 2]], dtype=int64)

In [106]:
np.argmin(a2) #the index on which the minimum value is residing in the array

0

In [107]:
random_array


array([[10, 13, 15],
       [15, 17, 17],
       [18, 10, 19]])

In [108]:
np.argmax(random_array,axis=1)
#the index on which maximum value of array is residing

array([2, 1, 2], dtype=int64)

In [109]:
np.argmax(random_array,axis=0)

array([2, 1, 2], dtype=int64)

In [129]:
from matplotlib.image import imread

panda = imread('images/numpy-panda.png')
print(type(panda))

<class 'numpy.ndarray'>


In [130]:
panda.shape

(2330, 3500, 3)

In [137]:
panda[2,2,0:2]

array([0.05490196, 0.10588235], dtype=float32)

In [141]:
car=imread('images/numpy-car-photo.png')

In [142]:
car.shape

(431, 575, 4)

In [145]:
car[1,1,:]

array([0.3137255 , 0.31764707, 0.27450982, 1.        ], dtype=float32)

In [147]:
car.size


991300

In [152]:
car.reshape(431,23,100).size

991300