# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'


import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()

a1=np.array([1,2,3])
# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[4,5,6],
             [7,8,9],
             [10,11,12],
             [13,14,15]
             
            ])

# Create a 3-dimensional Numpy array using np.array()

a3=np.array([
    [[1,2,3,4],
    [5,5,5,5]
    
    ],
    [[10,11,12,4],
         [5,5,5,5]

    ]
    
    
])

a1.ndim, a2.ndim,a3.ndim


(1, 2, 3)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)




In [5]:
# Attributes of 2-dimensional array


In [6]:
# Attributes of 3-dimensional array
a3.ndim,a3.dtype,a3.size,type(a2)


(3, dtype('int32'), 16, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

import pandas as pd

a=pd.DataFrame(a2, index=["A","B","C","D"], columns=["Aplha","Beta","Gamma"])

b=pd.DataFrame(np.random.randint(10,30,size=(5,3)))

c=pd.DataFrame(a3.reshape(8,2))
c




0   1
0   1   2
1   3   4
2   5   5
3   5   5
4  10  11
5  12   4
6   5   5
7   5   5

In [8]:
# Create an array of shape (10, 2) with only ones

np.random.rand(5,3)

np.random.randint(10,20,size=(5,3))


array([[17, 19, 13],
       [11, 19, 14],
       [19, 14, 17],
       [17, 14, 10],
       [12, 13, 17]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros

np.zeros(shape=(7,2,3))


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3

np.arange(0,100,3)


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)


np.random.randint(0,10,size=(7,2))

array([[4, 1],
       [4, 5],
       [9, 7],
       [0, 9],
       [6, 3],
       [0, 3],
       [1, 2]])

In [12]:

# Create a random array of floats between 0 & 1 of shape (3, 5)

np.random.rand(
3,5)


array([[0.33363956, 0.18589498, 0.49678263, 0.90317601, 0.17181049],
       [0.1800092 , 0.603994  , 0.72900076, 0.0882805 , 0.97705733],
       [0.31114056, 0.82093782, 0.93542031, 0.17408706, 0.98015815]])

In [13]:
# Set the random seed to 42

np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)


np.random.randint(0,10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?


Are the numbers in the array different or the same? Why do think this is?

In [14]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

a5=np.random.randint(1,10,size=(3,7))
np.unique(a5)

# Find the unique numbers in the array you just created


array([1, 2, 3, 4, 5, 7, 9])

In [15]:
# Find the 0'th index of the latest array you created

a5[0]
a5

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [16]:
# Get the first 2 rows of latest array you created
a5[0:2,:]




array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [17]:
# Get the first 2 values of the first 2 rows of the latest array

a5[0:2,0:2
  ]


array([[9, 1],
       [5, 3]])

In [18]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

rand=np.random.randint(0,10,size=(3,5))
rand



ones=np.ones((3,5))

In [19]:
# Add the two arrays together
rand+ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [20]:
# Create another array of ones of shape (5, 3)

ones2=np.ones((5,3))



In [21]:
# Try add the array of ones and the other most recent array together

ones2_reshape=ones2.reshape(3,5)

ones.shape,ones2_reshape.shape

added_ones=ones + ones2_reshape
added_ones


array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?


How would you fix it?

In [22]:
# Create another array of ones of shape (3, 5)
one3 =np.ones((3,5))




In [23]:
# Subtract the new array of ones from the other most recent array


added_ones+one3


array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [24]:
# Multiply the ones array with the latest array

ones*(added_ones+one3)




array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [25]:
# Take the latest array to the power of 2 using '**'


added_ones**2

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [26]:
# Do the same thing with np.square()


np.square(added_ones)

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [27]:
# Find the mean of the latest array using np.mean()

np.mean(added_ones)



2.0

In [28]:
# Find the maximum of the latest array using np.max()


np.max(added_ones)


2.0

In [29]:
# Find the minimum of the latest array using np.min()
np.min(added_ones)

2.0

In [30]:
# Find the standard deviation of the latest array

np.std (added_ones)



0.0

In [31]:
# Find the variance of the latest array


np.var(added_ones)

0.0

In [32]:
# Reshape the latest array to (3, 5, 1)

added_ones.reshape(3,5,1)



array([[[2.],
        [2.],
        [2.],
        [2.],
        [2.]],

       [[2.],
        [2.],
        [2.],
        [2.],
        [2.]],

       [[2.],
        [2.],
        [2.],
        [2.],
        [2.]]])

In [33]:
# Transpose the latest array

added_ones.T

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

What does the transpose do?

In [35]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


a6=np.random.randint(10,size=(3,3))
a7=np.random.randint(10,size=(3,2))

In [37]:
a6,a7


# Perform a dot product on the two newest arrays you created

np.dot(a6,a7)

array([[ 57,  49],
       [128, 135],
       [ 42,  68]])

In [42]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


a8=np.random.randint(10,size=(4,3))
a9=np.random.randint(10,size=(4,3))



In [46]:
# Perform a dot product on the two newest arrays you created

np.dot(a8,a9.T)




array([[ 66,  57,  54,  24],
       [ 83,  81,  86,  48],
       [102,  93,  96,  48],
       [ 62,  34,  58,   8]])

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both





Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [48]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


a10=np.random.randint(10,size=(5,2))
a11=np.random.randint(10,size=(5,2))


a10,a11

(array([[2, 9],
        [7, 5],
        [7, 8],
        [3, 0],
        [0, 9]]),
 array([[3, 6],
        [1, 2],
        [0, 4],
        [0, 7],
        [0, 0]]))

In [49]:
# Compare the two arrays with '>'
a10>a11


array([[False,  True],
       [ True,  True],
       [ True,  True],
       [ True, False],
       [False,  True]])

What happens when you compare the arrays with `>`?

In [50]:
# Compare the two arrays with '>='

a10>=a11

array([[False,  True],
       [ True,  True],
       [ True,  True],
       [ True, False],
       [ True,  True]])

In [51]:
# Find which elements of the first array are greater than 7


a10>7




array([[False,  True],
       [False, False],
       [False,  True],
       [False, False],
       [False,  True]])

In [52]:
# Which parts of each array are equal? (try using '==')

a10==a11


array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False]])

In [59]:
# Sort one of the arrays you just created in ascending order

np.sort(a10)

a10
a9

array([[9, 8, 4],
       [5, 3, 9],
       [6, 8, 6],
       [0, 0, 8]])

In [58]:
# Sort the indexes of one of the arrays you just created

np.argsort(a9)


array([[2, 1, 0],
       [1, 0, 2],
       [0, 2, 1],
       [0, 1, 2]], dtype=int64)

In [63]:
# Find the index with the maximum value in one of the arrays you've created

np.argmax(a9)



0

In [64]:
# Find the index with the minimum value in one of the arrays you've created

np.argmin(a9)

a9

array([[9, 8, 4],
       [5, 3, 9],
       [6, 8, 6],
       [0, 0, 8]])

In [65]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created



np.argmax(a9,1)

array([0, 2, 1, 2], dtype=int64)

In [66]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created

np.argmin(a9,0)


array([3, 3, 0], dtype=int64)

In [79]:
# Create an array of normally distributed random numbers

np.random.randn(5,2)


array([[-0.21432448, -0.68919421],
       [ 0.72783311, -0.61906936],
       [ 0.35615983, -0.02188087],
       [ 1.21805044, -0.38945802],
       [-0.44280234,  0.37822661]])

In [83]:
# Create an array with 10 evenly spaced numbers between 1 and 100

np.arange(1,101,10)
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.